// REAL Google reviews for ProtectHealth Insurance Agency (CID 11534166079504797199).
// Pulled verbatim from the live Google listing via Apify compass/Google-Maps-Reviews-Scraper
// on 2026-07-22 (290 newest scraped: 276 five-star / 4.9 overall / 703 total at pull time).
// Display-only — intentionally NO AggregateRating/Review schema (self-serving review markup risk).
// To refresh: re-run the scraper, regenerate this array. Dates shown as month/year so they never go stale.
export interface GoogleReview {
  name: string;
  stars: number;
  date: string;
  text: string;
}

export const GOOGLE_REVIEWS: GoogleReview[] = [
  { name: 'Al Molinaro', stars: 5, date: 'May 2025', text: 'I had an excellent experience with Robert and Jeff at ProtectHealth Insurance Agency. They are incredibly knowledgeable, and they took the time to understand my specific insurance needs. I was shopping around for coverage for my family and had called multiple places, but I could never get a straight answer. No one was willing to walk me through the process or explain how everything worked, and I felt completely lost. Thankfully, I came across ProtectHealth, and they were amazing. Robert took the time to go over everything in detail and patiently answered all of my questions. I feel very fortunate to have found these guys and highly recommend ProtectHealth to anyone looking for personalized, reliable insurance guidance' },
  { name: 'Yolanda Jackson', stars: 5, date: 'October 2025', text: 'My Healthcare Agent, Curtis McCall is an expert when it comes to the healthcare business, I know this from my personal experiences a few years ago and me and my family were in the market for other health/dental insurances and Mr. McCall truly helped us navigate our Healthcare needs.  I really appreciate Mr. McCall for his help and due diligence in helping us with this process.  Mr. McCall is  just a call/text away, and he offers Zoom consultations when requested.  Excellent service!' },
  { name: 'Ashton Aa', stars: 5, date: 'April 2026', text: 'Yvette is an amazing, wonderful, kind person. I was new to Nevada and the health care here , she took her time to explain things so I could really understand and was always available no matter the time or day. She also helped me to resolve an issue I was having with the pharmacy and insurance . We were on the phone for a while trying to sort things out and she never seemed bothered. She’s truly amazing .' },
  { name: 'Yudith Felix', stars: 5, date: 'April 2026', text: 'I had such a great experience with Pamela Noyes she is very kind, knowledgeable and very  very helpful and she goes above and beyond to make time to speak with you and explains everything and just makes sure you understand the whole process! She’s so amazing and you guys have a great great employee, please take care of her, she’s golden! Thank you Pam for all you do! You are so appreciated!' },
  { name: 'Veronica Rivera-Nunez', stars: 5, date: 'July 2025', text: 'Janet is one of the most amazing persons you will meet. She genuinly cares about what ever issue you bring to her. She will always smile and tell you that she will take care of  everything, and  makes sure my issues or concers are allways address on time. Now she is my to go person. her attitude is very positive and uplifting. I truly appreciate her!!!!' },
  { name: 'Aaron Nutten', stars: 5, date: 'February 2025', text: 'Stephanie was amazing! Super knowledgeable and able to transfer her wealth of knowledge effectively (and without making me feel like an idiot, which admittedly I was when it came to these new/uncharted waters). Very much appreciate her assistance in getting us sorted!' },
  { name: 'Javan', stars: 5, date: 'March 2025', text: 'After the death of my son and watching an insurance company go bankrupt right in the middle of the year, Janet was a trooper and helped me and my wife fine the right insurance company for our needs!! Thank you very much' },
  { name: 'Amber Gunn (Niel)', stars: 5, date: 'March 2025', text: 'Lawanda did amazing! after fighting to get insurance on my own, a quick call to her got me insurance in less than 30 minutes!!! She\'s my hero. Quick, Dependable, Friendly and Efficient. I\'m so happy i reached out.' },
  { name: 'Doris Moliga', stars: 5, date: 'November 2025', text: 'Brian Paradis is the best! I’ve have worked with him 2 years now and he’s always listened to what I need and can afford for my health insurance. I appreciate a Health Agent that listens to me and helps me with my options! Thank you!' },
  { name: 'Rachel Wren', stars: 5, date: 'September 2025', text: 'Thank you, Jeff Barton and ProtectHealth! Felt like family with the best service! Helped us navigate through - making it as easy as possible. The VERY best!' },
  { name: 'Stephen Kuo', stars: 5, date: 'April 2026', text: 'My partner and I have been in the capable hands of Lisa Drake for a few years now.  She\'s very knowledgable, helpful, and proactive.  Highly recommended.' },
  { name: 'Yvette Auger', stars: 5, date: 'April 2026', text: 'Lorraine Castillo is the best insurance agent, I use her for all my personal and real estate clients insurance policies. She is the only agent I trust in Nevada.' },
  { name: 'Monica Vanegas', stars: 5, date: 'June 2025', text: 'Jeff is so thorough and easy to work with.  I\'m happy to have an agent who goes above and beyond to make sure my questions are answered.  Thanks for always following up and checking in!' },
  { name: 'Katie Rose Matthews', stars: 5, date: 'January 2026', text: 'Brian was amazing and took the time to walk me through everything step by step and answer any questions I had.' },
  { name: 'Loniafe Bruno', stars: 5, date: 'April 2026', text: 'Tammy did an excellent job as usual. She always goes out of her way and spends time with us so we understand the details.' },
  { name: 'Kim Hunter-Smith', stars: 5, date: 'April 2026', text: 'Great personal service. I can’t say enough about Pam N., she is fantastic!' },
  { name: 'Andy Diec', stars: 5, date: 'November 2025', text: 'Christopher helped me find the best plan to meet my needs. He is very easy to work with and I would recommend him to other people!' },
  { name: 'Keith Irby', stars: 5, date: 'September 2025', text: 'Lorraine Castillo was my agent, very professional and detailed. Great Agent, I will be recommending her services.' },
  { name: 'Aaron Walker', stars: 5, date: 'April 2025', text: 'What can I say the help and dedication is above and beyond and the staff have actual compassion and understanding for my needs and situations.' },
  { name: 'Michelle', stars: 5, date: 'May 2026', text: 'Protect Health was very professional and helpful, especially Michelle Brunson, top notch agent!!!' },];
